name: Supernova Token Sync

on:
  push:
    branches:
      - main
    paths:
      - 'tokens.json' 
      
jobs:
  sync_tokens:
    runs-on: ubuntu-latest
    steps:
      # 1. Checks out the repository
      - uses: actions/checkout@v4 
      
      # 2. Add this NEW step to install the missing library
      - name: Install System Dependencies
        run: sudo apt-get update && sudo apt-get install -y libsecret-1-0

      # 3. Installs the Supernova CLI tool
      - name: Install Supernova CLI
        run: npm install -g @supernovaio/cli
        
      # 4. Runs the sync command (the command itself is correct)
      - name: Synchronize tokens with Supernova
        run: supernova sync-tokens \
          --apiKey=${{ secrets.SUPERNOVA_ACCESS_TOKEN }} \
          --designSystemId="https://app.supernova.io/536934-pps/578018-pps-design-system/609622-shared-draft" \
          --tokenFilePath="./tokens.json"
