name: Supernova Token Sync

on:
  push:
    branches:
      - main
    paths:
      - 'tokens.json'

jobs:
  sync_tokens:
    runs-on: ubuntu-latest
    steps:
      # 1. Check out the repository
      - uses: actions/checkout@v4

      # 2. Install system dependencies (required for keychain handling)
      - name: Install System Dependencies
        run: sudo apt-get update && sudo apt-get install -y libsecret-1-0

      # 3. Install the Supernova CLI
      - name: Install Supernova CLI
        run: npm install -g @supernovaio/cli

      # 4. Create Supernova config file
      - name: Create Supernova config
        run: |
          cat <<EOF > supernova.config.json
          {
            "version": "1.0",
            "designSystemId": "609622-shared-draft",
            "tokenFilePath": "./tokens.json"
          }
          EOF

      # 5. Sync tokens with Supernova
      - name: Synchronize tokens with Supernova
        run: supernova sync-tokens \
          --apiKey="${{ secrets.SUPERNOVA_ACCESS_TOKEN }}" \
          --configFilePath="./supernova.config.json"
